---

- stat: path=/usr/bin/php
  register: php_stat

- name: Install PPAs
  apt_repository: repo='ppa:ondrej/php' update_cache=yes state=present

- name: Install PHP
  apt: pkg=php7.1-cli force=yes state=latest update_cache=yes
  when: php_stat.stat.exists == False
 
- name: Install PHP modules
  apt: pkg={{item}} state=latest
  with_items:
    - php7.1-mysql
    - php7.1-mcrypt
    - php7.1-curl
    - php7.1-intl
    - php7.1-mbstring  

- stat: path=/usr/local/bin/composer
  register: composer_stat

- name: Download PHP Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer_installer
  when: composer_stat.stat.exists == False 

- name: Install PHP Composer
  become: true
  shell: php /tmp/composer_installer --install-dir=/usr/local/bin --filename="composer"
  args:
    creates: /usr/usr/local/bin/composer
  when: composer_stat.stat.exists == False

